(() => {
  const palette = {paid:{line:'#35c98b',bg:'rgba(53,201,139,.16)',fg:'#69e6ac'},due:{line:'#22d3ee',bg:'rgba(34,211,238,.16)',fg:'#67e8f9'},pending:{line:'#22d3ee',bg:'rgba(34,211,238,.16)',fg:'#67e8f9'},partial:{line:'#f6b84a',bg:'rgba(246,184,74,.16)',fg:'#ffd176'},overdue:{line:'#f16d64',bg:'rgba(241,109,100,.16)',fg:'#ff9d96'},planned:{line:'#8f9ab5',bg:'rgba(143,154,181,.15)',fg:'#bec8df'},advance:{line:'#8f9ab5',bg:'rgba(143,154,181,.15)',fg:'#bec8df'}};
  function cachedData(){try{return JSON.parse(localStorage.getItem('densel_data_cache')||'{}')}catch(_){return {}}}
  function fallbackStatus(label){const t=String(label||'').trim().toLowerCase();if(t.includes('просроч'))return'overdue';if(t.includes('частич'))return'partial';if(t.includes('оплачен'))return'paid';if(t.includes('аванс')||t.includes('будущ'))return'planned';return'due'}
  function paymentStatus(row,payments){const payment=payments.find(p=>String(p.id)===String(row.dataset.id)),rules=window.DenselPaymentRules;return payment&&rules&&typeof rules.status==='function'?rules.status(payment):fallbackStatus(row.querySelector('.badge')?.textContent)}
  function applyPaymentStatusColors(){const root=document.getElementById('adminPaymentsList');if(!root)return;const payments=cachedData().payments||[];root.querySelectorAll('.payment-row').forEach(row=>{const status=paymentStatus(row,payments),color=palette[status]||palette.due;row.style.borderLeft=`3px solid ${color.line}`;row.style.paddingLeft='10px';row.style.transition='none';const badge=row.querySelector('.badge');if(!badge)return;badge.style.background=color.bg;badge.style.color=color.fg;badge.style.border=`1px solid ${color.line}`;badge.style.transition='none';badge.dataset.paymentStatus=status})}
  function install(){if(typeof renderAdminPayments!=='function'||window.__denselAdminPaymentColorsInstalled)return false;const nativeRender=renderAdminPayments;window.__denselAdminPaymentColorsInstalled=true;renderAdminPayments=function(...args){const result=nativeRender.apply(this,args);applyPaymentStatusColors();return result};applyPaymentStatusColors();return true}
  [0,200,700,1400].forEach(delay=>setTimeout(install,delay));window.DenselAdminPaymentColors={refresh:applyPaymentStatusColors};
})();
