(() => {
  const rules = () => window.DenselPaymentRules;
  const data = () => { try { return JSON.parse(localStorage.getItem('densel_data_cache') || '{}'); } catch (_) { return {}; } };
  const money = value => Number(value || 0).toLocaleString('ru-RU',{maximumFractionDigits:2}) + ' ₽';
  const esc = value => { const e=document.createElement('span'); e.textContent=String(value ?? ''); return e.innerHTML; };
  const month = value => { const names=['янв','фев','мар','апр','май','июн','июл','авг','сен','окт','ноя','дек']; const [y,m]=String(value||'').split('-'); return names[Number(m)-1] ? `${names[Number(m)-1]} ${y}` : value; };
  const labels = {paid:'Оплачено',paid_early:'Оплачено заранее',partial:'Оплачено частично',due:'К оплате',overdue:'Просрочено'};
  function historyRows(list) {
    const d=data(), providers=Object.fromEntries((d.providers||[]).map(x=>[x.id,x]));
    return list.map(raw=>{ const p=rules().normalized(raw), st=rules().status(raw), pr=providers[raw.providerId]||{}, bal=rules().balance(raw); const due=st==='due' ? `К оплате до ${esc(p.dueDate||'—')}` : labels[st]; return `<article style="padding:12px 0;border-bottom:1px solid rgba(128,128,128,.16)"><div style="display:flex;justify-content:space-between;gap:12px"><strong>${esc(pr.name||'Услуга')}</strong><span class="badge ${st==='overdue'?'pending':'paid'}">${esc(due)}</span></div><div class="muted" style="margin-top:5px">Расчётный месяц: ${esc(month(p.billingMonth))}</div><div class="muted">Начислено: ${money(p.amount)}${p.paidAmount ? ` · Оплачено: ${money(p.paidAmount)}` : ''}${bal && st!=='due' ? ` · Остаток: ${money(bal)}` : ''}</div>${p.paymentDate ? `<div class="muted">Дата оплаты: ${esc(p.paymentDate)}</div>` : ''}</article>`; }).join('') || '<p class="muted">Для выбранного фильтра записей нет.</p>';
  }
  function openHistory() {
    document.getElementById('specHistoryOverlay')?.remove();
    const overlay=document.createElement('div'); overlay.id='specHistoryOverlay'; overlay.style.cssText='position:fixed;inset:0;z-index:10000;background:rgba(10,15,30,.72);display:flex;align-items:flex-end;justify-content:center;padding:12px;box-sizing:border-box';
    overlay.innerHTML='<section style="width:min(700px,100%);max-height:88vh;overflow:auto;background:#10182b;color:#f5f7ff;border-radius:20px;padding:18px;box-sizing:border-box"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><div><h3 style="margin:0">Платежи</h3><div class="muted">История, фильтры и сортировка</div></div><button type="button" id="specHistoryClose" class="btn ghost">Закрыть</button></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin:15px 0"><select id="specHistoryStatus" class="select" style="flex:1;min-width:145px"><option value="all">Все статусы</option><option value="paid">Оплачено</option><option value="paid_early">Оплачено заранее</option><option value="partial">Частично</option><option value="due">К оплате</option><option value="overdue">Просрочено</option></select><select id="specHistorySort" class="select" style="flex:1;min-width:145px"><option value="payment-desc">Оплата: новые сверху</option><option value="payment-asc">Оплата: старые сверху</option><option value="due-asc">Срок: ближайшие сверху</option><option value="due-desc">Срок: дальние сверху</option></select></div><div id="specHistoryRows"></div></section>';
    const draw=()=>{ const filter=overlay.querySelector('#specHistoryStatus').value, sort=overlay.querySelector('#specHistorySort').value; const r=rules(); let list=(data().payments||[]).filter(p=>r.isHistoryStatus(r.status(p))).filter(p=>filter==='all'||r.status(p)===filter); const field=sort.startsWith('payment')?'paymentDate':'dueDate'; list.sort((a,b)=>{const av=String(r.normalized(a)[field]||''), bv=String(r.normalized(b)[field]||''); return sort.endsWith('asc')?av.localeCompare(bv):bv.localeCompare(av);}); overlay.querySelector('#specHistoryRows').innerHTML=historyRows(list); };
    overlay.querySelector('#specHistoryClose').onclick=()=>overlay.remove(); overlay.addEventListener('click',e=>{if(e.target===overlay)overlay.remove();}); overlay.querySelector('#specHistoryStatus').onchange=draw; overlay.querySelector('#specHistorySort').onchange=draw; document.body.appendChild(overlay); draw();
  }
  document.addEventListener('click',event=>{ if(!event.target.closest?.('#historyBtn-admin,#historyBtn-client')) return; event.preventDefault(); event.stopImmediatePropagation(); openHistory(); },true);
  window.DenselPaymentsTools = {...(window.DenselPaymentsTools||{}),openHistory};
})();
