(() => {
  const KEY='densel_data_cache', money=n=>(Math.round(Number(n||0)*100)/100).toLocaleString('ru-RU',{maximumFractionDigits:2})+' ₽';
  const period=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`, label=p=>{const m=['янв','фев','мар','апр','май','июн','июл','авг','сен','окт','ноя','дек'],[y,mo]=String(p||'').split('-');return m[Number(mo)-1]?`${m[Number(mo)-1]} ${y}`:p};
  const data=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(_){return {}}};
  function paidTotal(){const cur=period(new Date());return(data().payments||[]).filter(p=>String(p.paidDate||'').startsWith(cur)).reduce((s,p)=>s+Number(p.amountPaid||0),0)}
  function fixPaidSummary(){const cur=period(new Date()),total=money(paidTotal());document.querySelectorAll('#clientSummary .summary-card,#adminSummary .summary-card').forEach(card=>{const l=card.querySelector('.label');if(!l||!/оплач/i.test(l.textContent||''))return;const v=card.querySelector('.value'),s=card.querySelector('.sub');if(v)v.textContent=total;if(s)s.textContent=`По датам оплат за ${label(cur)}`})}
  function openHistory(){const d=data(),o=document.createElement('div');o.id='paymentHistoryOverlay';o.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(10,15,30,.72);display:flex;align-items:flex-end;justify-content:center;padding:12px;box-sizing:border-box';const rows=()=>{const ps=d.payments||[],pr=Object.fromEntries((d.providers||[]).map(x=>[x.id,x]));return ps.map(p=>`<div style="padding:11px 0;border-bottom:1px solid rgba(128,128,128,.16)"><strong>${pr[p.providerId]?.name||'Услуга'}</strong><div class="muted">${label(p.period)} · Оплачено: ${money(p.amountPaid)}</div></div>`).join('')||'<p class="muted">Операций нет.</p>'};o.innerHTML=`<section style="width:min(680px,100%);max-height:88vh;overflow:auto;background:#10182b;color:#f5f7ff;border-radius:20px;padding:18px"><div style="display:flex;justify-content:space-between"><h3 style="margin:0">История платежей</h3><button type="button" id="historyClose" class="btn ghost">Закрыть</button></div><div style="margin-top:12px">${rows()}</div></section>`;o.querySelector('#historyClose').onclick=()=>o.remove();o.onclick=e=>{if(e.target===o)o.remove()};document.body.appendChild(o)}
  function addTools(id,scope){const list=document.getElementById(id),barId=`paymentTools-${scope}`;if(!list||document.getElementById(barId))return;const bar=document.createElement('div');bar.id=barId;bar.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px';bar.innerHTML=`<button type="button" class="btn secondary small">↕ История и сортировка</button>${scope==='admin'?'<button type="button" class="btn ghost small">⇩ Скачать выгрузку</button>':''}`;list.parentNode.insertBefore(bar,list);bar.querySelector('button').onclick=openHistory;bar.querySelectorAll('button')[1]?.addEventListener('click',()=>{const b=new Blob([JSON.stringify(data(),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=`densel-payments-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)})}
  function apply(){addTools('adminPaymentsList','admin');addTools('paymentsList','client');fixPaidSummary()}
  function install(){if(typeof renderAdminDashboard==='function'&&!window.__denselPaymentSummaryFixed){const native=renderAdminDashboard;window.__denselPaymentSummaryFixed=true;renderAdminDashboard=function(...a){const r=native.apply(this,a);apply();return r}}apply()}
  [0,250,800,1600].forEach(ms=>setTimeout(install,ms));window.DenselPaymentsTools={apply,openHistory};
})();
