(() => {
  const DATA_KEY = 'densel_data_cache';
  const fmtMoney = n => (Math.round(Number(n || 0) * 100) / 100).toLocaleString('ru-RU', {maximumFractionDigits:2}) + ' ₽';
  const esc = value => { const n=document.createElement('span'); n.textContent=String(value ?? ''); return n.innerHTML; };
  const period = d => `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;
  const periodLabel = p => { const m=['янв','фев','мар','апр','май','июн','июл','авг','сен','окт','ноя','дек']; const [y,mo]=String(p||'').split('-'); return m[Number(mo)-1] ? `${m[Number(mo)-1]} ${y}` : p; };
  function data() { try { return JSON.parse(localStorage.getItem(DATA_KEY) || '{}'); } catch (_) { return {}; } }
  function status(p) { const paid=Number(p.amountPaid||0), due=Number(p.amountDue||0), today=new Date(); today.setHours(0,0,0,0); if (paid >= due && due > 0) return p.period > period(new Date()) ? 'advance' : 'paid'; if (p.dueDate && new Date(p.dueDate) < today) return 'overdue'; if (paid > 0) return 'partial'; return 'pending'; }
  function statusLabel(s) { return ({paid:'Оплачено',advance:'Аванс',overdue:'Просрочено',partial:'Частично',pending:'Ожидается'})[s] || s; }
  function paymentRows(list) { const d=data(), providers=Object.fromEntries((d.providers||[]).map(x=>[x.id,x])); return list.map(p=>{ const pr=providers[p.providerId]||{}; return `<div style="padding:11px 0;border-bottom:1px solid rgba(128,128,128,.16)"><div style="display:flex;justify-content:space-between;gap:10px"><strong>${esc(pr.name||'Услуга')}</strong><strong>${fmtMoney(p.amountPaid||0)}</strong></div><div class="muted">Начисление: ${esc(periodLabel(p.period))} · Оплата: ${esc(p.paidDate||'—')} · ${esc(statusLabel(status(p)))}</div></div>`; }).join('') || '<p class="muted">Подходящих операций нет.</p>'; }
  function openHistory() {
    document.getElementById('paymentHistoryOverlay')?.remove();
    const overlay=document.createElement('div'); overlay.id='paymentHistoryOverlay'; overlay.style.cssText='position:fixed;inset:0;z-index:9999;background:rgba(10,15,30,.72);display:flex;align-items:flex-end;justify-content:center;padding:12px;box-sizing:border-box';
    overlay.innerHTML='<div style="width:min(680px,100%);max-height:88vh;overflow:auto;background:#10182b;color:#f5f7ff;border-radius:20px;padding:18px;box-sizing:border-box"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><h3 style="margin:0">История платежей</h3><button type="button" id="historyClose" class="btn ghost">Закрыть</button></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin:14px 0"><select id="historyStatus" class="select" style="flex:1;min-width:150px"><option value="all">Все статусы</option><option value="paid">Оплачено</option><option value="pending">Ожидается</option><option value="partial">Частично</option><option value="overdue">Просрочено</option><option value="advance">Аванс</option></select><select id="historySort" class="select" style="flex:1;min-width:150px"><option value="paid-desc">Оплата: сначала новые</option><option value="paid-asc">Оплата: сначала старые</option><option value="due-desc">Срок: сначала новые</option><option value="due-asc">Срок: сначала старые</option></select></div><div id="historyRows"></div></div>';
    const draw=()=>{ const filter=overlay.querySelector('#historyStatus').value, sort=overlay.querySelector('#historySort').value; let list=(data().payments||[]).filter(p=>filter==='all'||status(p)===filter); const field=sort.startsWith('paid')?'paidDate':'dueDate'; list.sort((a,b)=>{const av=String(a[field]||''),bv=String(b[field]||''); return sort.endsWith('asc')?av.localeCompare(bv):bv.localeCompare(av);}); overlay.querySelector('#historyRows').innerHTML=paymentRows(list); };
    overlay.querySelector('#historyClose').onclick=()=>overlay.remove(); overlay.addEventListener('click',e=>{if(e.target===overlay) overlay.remove();}); overlay.querySelector('#historyStatus').onchange=draw; overlay.querySelector('#historySort').onchange=draw; document.body.appendChild(overlay); draw();
  }
  function exportPayments() { const d=data(); const out={format:'densel-payments-export',version:1,exportedAt:new Date().toISOString(),providers:d.providers||[],payments:d.payments||[]}; const blob=new Blob([JSON.stringify(out,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a'); a.href=url; a.download=`densel-payments-${new Date().toISOString().slice(0,10)}.json`; a.click(); setTimeout(()=>URL.revokeObjectURL(url),1000); }
  function addTools(listId, scope) { const list=document.getElementById(listId); if(!list) return; const id=`paymentTools-${scope}`; if(document.getElementById(id)) return; const bar=document.createElement('div'); bar.id=id; bar.style.cssText='display:flex;gap:8px;flex-wrap:wrap;margin:0 0 12px'; bar.innerHTML=`<button type="button" class="btn secondary small" id="historyBtn-${scope}">↕ История и сортировка</button>${scope==='admin'?'<button type="button" class="btn ghost small" id="exportPaymentsBtn">⇩ Скачать выгрузку</button>':''}`; list.parentNode.insertBefore(bar,list); bar.querySelector(`#historyBtn-${scope}`).onclick=openHistory; bar.querySelector('#exportPaymentsBtn')?.addEventListener('click',exportPayments); }
  function fixPaidSummary() { const d=data(), cur=period(new Date()); const total=(d.payments||[]).filter(p=>String(p.paidDate||'').startsWith(cur)).reduce((sum,p)=>sum+Number(p.amountPaid||0),0); document.querySelectorAll('#clientSummary .summary-card').forEach(card=>{ const label=card.querySelector('.label'); if(label && /оплач/i.test(label.textContent||'')){ const value=card.querySelector('.value'); if(value && value.textContent!==fmtMoney(total)) value.textContent=fmtMoney(total); const sub=card.querySelector('.sub'); if(sub && sub.textContent!==`По датам оплат за ${periodLabel(cur)}`) sub.textContent=`По датам оплат за ${periodLabel(cur)}`; }}); }
  function apply() { document.getElementById('bulkPaymentsBtn')?.remove(); addTools('adminPaymentsList','admin'); addTools('paymentsList','client'); fixPaidSummary(); }
  [100,500,1200,2500].forEach(ms=>setTimeout(apply,ms)); document.addEventListener('click',()=>setTimeout(apply,80),true); document.addEventListener('change',()=>setTimeout(apply,80),true); window.DenselPaymentsTools={apply,openHistory,exportPayments};
})();
